### ISSUE TITLE
Implement Unit Testing for Generation wallet and Import Wallet

### ISSUE THREAD

**Issue by pavankanteti** [Polkadex-Substrate/polkadex-mobile-app#31]
As a developer
- I want to implement unit testing for all the issues
- So that I can meet the DoD

DoD:
Unit testing

**Comment by simonsso** [comment]
Unit tests is a tool which will make development easier if done in parallel with the code it is a pain to retrofit. @AdrielVBomfim please consider to work with items from this ticket to solve #22 ans #23

**Comment by AdrielVBomfim** [comment]
Yes I agree that the unit tests should be done in parallel. The tests in this particular case will be made separately because they refer to not only the Import Wallet Epic but also the Generation Wallet Epic, which was made on the last sprint. Once I cover what has been integrated with unit tests, every feature from now on should be made in parallel with its unit tests.
